[versions]
androidx-room = "2.8.3"
core-ktx = "1.17.0"

compose-bom = "2025.10.01"
compose-material3 = "1.4.0"
activity-compose = "1.11.0"
lifecycle-viewmodel-compose = "2.9.4"

espresso-core = "3.7.0"
junit = "4.13.2"
junit-version = "1.3.0"

lifecycle-runtime-ktx = "2.9.4"
navigation-compose = "2.9.5"

firebase-auth = "24.0.1"
firebase-bom = "34.5.0"
firebase-firestore = "26.0.2"

colorpicker = "1.1.2"
retrofit = "3.0.0"
converterGson = "3.0.0"

kotlin = "2.2.21"
agp = "8.13.0"
uiUnit = "1.9.4"
ksp = "2.2.20-2.0.4"


[libraries]
androidx-core-ktx                           = { group = "androidx.core",                name = "core-ktx",                  version.ref = "core-ktx"    }
androidx-compose-material-icons-extended    = { group = "androidx.compose.material",    name = "material-icons-extended"                                }

# room db
androidx-room-ktx       = { module = "androidx.room:room-ktx",      version.ref = "androidx-room" }
androidx-room-runtime   = { module = "androidx.room:room-runtime",  version.ref = "androidx-room" }
androidx-room-compiler  = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }

# composables (https://developer.android.com/develop/ui/compose/setup#kotlin)
androidx-compose-bom       = { group = "androidx.compose",              name = "compose-bom",  version.ref = "compose-bom"          }
androidx-compose-ui        = { group = "androidx.compose.ui",           name = "ui"                                                 }
androidx-compose-material3 = { group = "androidx.compose.material3",    name = "material3",    version.ref = "compose-material3"    }

# integration with activities & viewmodels
androidx-activity-compose               = { group = "androidx.activity",    name = "activity-compose",              version.ref = "activity-compose"            }
androidx-lifecycle-viewmodel-compose    = { group = "androidx.lifecycle",   name = "lifecycle-viewmodel-compose",   version.ref = "lifecycle-viewmodel-compose" }
# + runtime lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

androidx-ui-graphics        = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }


# preview support
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"  }
androidx-compose-ui-tooling         = { group = "androidx.compose.ui", name = "ui-tooling"          }

# testing
androidx-compose-ui-test-junit4     = { group = "androidx.compose.ui",      name = "ui-test-junit4"                                 }
androidx-compose-ui-test-manifest   = { group = "androidx.compose.ui",      name = "ui-test-manifest"                               }
androidx-espresso-core              = { group = "androidx.test.espresso",   name = "espresso-core", version.ref = "espresso-core"    }

# junit
junit           = { group = "junit",                name = "junit", version.ref = "junit"           }
androidx-junit  = { group = "androidx.test.ext",    name = "junit", version.ref = "junit-version"   }

#firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebase-firestore" }

# colorpicker
colorpicker = { group = "com.github.skydoves", name = "colorpicker-compose", version.ref = "colorpicker"}

# http & api libs
# https://square.github.io/retrofit/download/
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
# android studio refactor from https://github.com/square/retrofit/blob/trunk/retrofit-converters/gson/README.md
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "uiUnit" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services" }

